### ISSUE TITLE
Batch note editing- 2.1 clipboard support not working

### ISSUE THREAD

**Issue by Z1839** [glutanimate/anki-addons-misc#79] opened 2019-03-06 13:31 UTC
Batch note editing. Anki 2.1.9. 

I can't seem to use the paste from clipboard feature on 2.1. I get this error:
"Debug info:
Anki 2.1.9 (ae67c976) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.3
Flags: frz=True ao=True sv=2
Add-ons possibly involved: Batch Note Editing

Caught exception:
  File "/Users/NAME/Library/Application Support/Anki2/addons21/291119185/browser_batch_edit.py", line 101, in _insertMedia
    media_file = self._getClip()
  File "/Users/NAME/Library/Application Support/Anki2/addons21/291119185/browser_batch_edit.py", line 135, in _getClip
    return unicode(image_path)
<class 'NameError'>: name 'unicode' is not defined"

However, once I click the paperclip icon again, i'm able to search my folders for my file.

**Comment by glutanimate** [comment] 2019-04-18 09:43
Thanks for the report! I'll look into this soon.

**Comment by glutanimate** [comment] 2019-04-18 10:11
Marking this as a duplicate of #58. Please feel free to follow the progress there.

**Closed by glutanimate** 2019-04-18 10:11 UTC
Labels: anki21, bug, duplicate, regression
