### ISSUE TITLE
[Progress Bar] actual reviews and progress not lining up

### ISSUE THREAD

**Issue by natg101** [glutanimate/anki-addons-misc#33] opened 2017-12-11 14:41 UTC
Any way to fix this? I did one deck and it worked fine. The next deck I did all 100 cards and yet the progress bar showed 38%. I didn't leave the deck once starting. On the anki add on page other users have reported similar issues

thanks!

edit- i have night mode downloaded. When turned off the bar seems to work better but still not accurate. If there is code to change will someone explain the steps to fix and use both progress bar + night mode?

**Comment by coco1602** [comment] 2018-02-03 23:09
I also have some problems with this addon. The progress bar often goes backwards even when I press Good several times... ?!

**Comment by Alien714** [comment] 2018-02-14 00:43
Same thing here https://i.imgur.com/dQs7Hky.png

**Comment by glutanimate** [comment] 2018-02-24 11:52
Thanks for the reports, guys. The add-on currently follows a very basic approach to calculating the remaining card totals and progress through the deck, which does not take into consideration some of the intricacies involved in this like review limits, review lapses, different options groups for different decks, or sibling burying. This can lead to inconsistencies like the one described in this issue report or glutanimate/anki-addons-misc#21.

A fix will likely require a significant redesign of the add-on, so this is something I won't be able to do quickly. (As a quick aside: I didn't write this add-on. I only took over its maintenance once the original author disappeared. So most if not all of these issues stem from the original codebase.)

My suggestion in the meanwhile for producing the most accurate results would be to:

1. Go through your reviews deck by deck if you can
2. Disable tracking the progress of cards in learning by setting [this variable](https://github.com/glutanimate/anki-addons-misc/blob/master/src/reviewer_progress_bar/reviewer_progress_bar.py#L31) to False

**Comment by glutanimate** [comment] 2018-08-22 08:01
Closing this as a duplicate of glutanimate/anki-addons-misc#21. Please refer to my latest comment there for updates on a potential fix for this issue in the Progress Bar add-on.

**Closed by glutanimate** 2018-08-22 08:01 UTC
Labels: bug, duplicate
