### ISSUE TITLE
[Extended Card Stats During Review] Sidebar is too narrow and can't expand it.

### ISSUE THREAD

**Issue by hodorofmordor** [glutanimate/anki-addons-misc#42] opened 2018-02-25 14:11 UTC
## Which add-on is affected?

[ Please mention the add-on in the issue title as follows: "[Add-on name] My issue" ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [X ] In case of a bug: Have you tried restarting Anki?
- [ X] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [X ] Did you check the add-on description on AnkiWeb for known issues?
- [X ] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

[ The addon appears to work fine but the sidebar it generates it too narrow. There is also no option to expand the sidebar. I have added an image below. ]

https://imgur.com/a/Q8DLN

**Comment by glutanimate** [comment] 2018-02-25 14:13
Thanks for the report. The sidebar issue is caused by the Progress Bar add-on (see #39). Temporarily uninstalling it should allow you to resize the panel again.

**Comment by glutanimate** [comment] 2019-04-18 10:36
Closing this for now as the fix will have to be implemented on Progress Bar's side.

**Closed by glutanimate** 2019-04-18 10:36 UTC
Labels: add-on conflict
